### ISSUE TITLE
works in CMD but not in GIT BASH

### ISSUE THREAD

**Issue by yairEO** [feross/beepbeep#5] opened 2015-12-17 12:34 UTC
is it suppose to work in GIT BASH?

**Comment by feross** [comment] 2015-12-17 12:40
What is GIT BASH?

**Comment by yairEO** [comment] 2015-12-17 23:49
in windows when you install GIT you also install GIT BASH, it's a shell

**Comment by dskrepps** [comment] 2015-12-18 00:08
Works in git bash on my Windows 8.1 system. All beepbeep does is write \x07 to stdout so the issue is probably with your operating system. Make sure your speakers are on rather than relying solely on your motherboard's system bell. On the other hand some motherboards don't even have a system bell and your OS might not be configured to play a sound.

**Comment by feross** [comment] 2015-12-25 07:18
Closing, since this module just writes one character to stdout. It's up to your operating system and shell to the right thing with it.

**Closed by feross** 2015-12-25 07:18 UTC

**Comment by jcbize** [comment] 2016-08-27 10:25
If you're using **ConEmu** or **Cmder** as your terminal for Git Bash -- and a whole lot of us are -- note that its "Suppress bell" feature is _ON_ by default. You'll need to disable it for beepbeep to work.

See http://conemu.github.io/en/SettingsFeatures.html for more details.
